import { useEffect, useState } from "react";
import { Check } from "lucide-react";
import { useStudio } from "./store/studio";
import type { Project, WorkflowSettings } from "./types";

export function WorkflowSettingsPanel({ project }: { project: Project }) {
  const { busy, updateWorkflow, updateRuntime } = useStudio();
  const [workflow, setWorkflow] = useState<WorkflowSettings>(project.workflow);
  const [cellWidth, setCellWidth] = useState(project.runtime.cellWidth);
  const [cellHeight, setCellHeight] = useState(project.runtime.cellHeight);
  const [pivotX, setPivotX] = useState(project.runtime.pivotX);
  const [pivotY, setPivotY] = useState(project.runtime.pivotY);
  useEffect(() => { setWorkflow(project.workflow); }, [project.id, project.workflow]);
  useEffect(() => { setCellWidth(project.runtime.cellWidth); setCellHeight(project.runtime.cellHeight); setPivotX(project.runtime.pivotX); setPivotY(project.runtime.pivotY); }, [project.id, project.runtime]);
  const workflowValid = Number.isInteger(workflow.kColors) && workflow.kColors >= 2 && workflow.kColors <= 256 && /^#[\da-fA-F]{6}$/.test(workflow.chroma) && Number.isInteger(workflow.sheetColumns) && workflow.sheetColumns >= 1 && workflow.sheetColumns <= 16 && Number.isInteger(workflow.sheetRows) && workflow.sheetRows >= 1 && workflow.sheetRows <= 16 && workflow.typicalNudgeRangePx >= 0 && workflow.typicalNudgeRangePx <= 5;
  const runtimeValid = [cellWidth, cellHeight, pivotX, pivotY].every(Number.isInteger) && cellWidth >= 16 && cellWidth <= 1024 && cellHeight >= 16 && cellHeight <= 1024 && pivotX >= 0 && pivotX < cellWidth && pivotY >= 0 && pivotY < cellHeight;
  return <details className="pose-panel workflow-settings-panel">
    <summary>Project workflow settings <small>{project.preset === "kangi-fight" ? "horizontal 128×128 cells" : `${project.runtime.cellWidth * project.workflow.sheetColumns}×${project.runtime.cellHeight * project.workflow.sheetRows} full draft sheet`} · {project.workflow.upscaleMode === "manual-handoff" ? "manual upscale" : "automatic"}</small></summary>
    <p className="animation-hint">Repo starting point: 256 colors preserves subtle palette while flattening sub-pixel noise. Snap runs once per recovered frame, never on the entire board. Generic starts at 5×2 cells of 256×256 (1280×512); KangiFight keeps its approved 128×128 pivot (64,112). Manual alignment is final 1–2 px polish, not a substitute for normalization.</p>
    <div className="batch-controls"><label>Snap colors<input className="text-input" type="number" min="2" max="256" value={workflow.kColors} onChange={e => setWorkflow({ ...workflow, kColors: Number(e.target.value) })} /></label><label>Chroma / key color<input className="text-input" value={workflow.chroma} onChange={e => setWorkflow({ ...workflow, chroma: e.target.value })} /></label><label>Upscale mode<select className="text-input" value={workflow.upscaleMode} onChange={e => setWorkflow({ ...workflow, upscaleMode: e.target.value as WorkflowSettings["upscaleMode"] })}><option value="automatic">Automatic inside snapper</option><option value="manual-handoff">Manual external handoff</option></select></label></div>
    <div className="batch-controls"><label>Sheet columns<input className="text-input" type="number" min="1" max="16" disabled={project.preset === "kangi-fight"} value={workflow.sheetColumns} onChange={e => setWorkflow({ ...workflow, sheetColumns: Number(e.target.value) })} /></label><label>Sheet rows<input className="text-input" type="number" min="1" max="16" disabled={project.preset === "kangi-fight"} value={workflow.sheetRows} onChange={e => setWorkflow({ ...workflow, sheetRows: Number(e.target.value) })} /></label><label>Typical nudge (px)<input className="text-input" type="number" min="0" max="5" value={workflow.typicalNudgeRangePx} onChange={e => setWorkflow({ ...workflow, typicalNudgeRangePx: Number(e.target.value) })} /></label><label>Anchor mode<select className="text-input" disabled={project.preset === "kangi-fight"} value={workflow.anchorMode} onChange={e => { const mode = e.target.value as WorkflowSettings["anchorMode"]; setWorkflow({ ...workflow, anchorMode: mode }); if (mode === "bottom-center") { setPivotX(Math.floor(cellWidth / 2)); setPivotY(cellHeight - 1); } }}><option value="bottom-center">Bottom-center</option><option value="custom">Custom pivot</option></select></label></div>
    <div className="animation-actions"><label><input type="checkbox" checked={workflow.manualPolishEnabled} onChange={e => setWorkflow({ ...workflow, manualPolishEnabled: e.target.checked })} /> Manual aligner polish</label><label><input type="checkbox" checked={workflow.greenFringeDespeckle} onChange={e => setWorkflow({ ...workflow, greenFringeDespeckle: e.target.checked })} /> Green fringe cleanup</label><button className="button secondary" disabled={busy || !workflowValid} onClick={() => void updateWorkflow(workflow)}><Check size={15} /> Save workflow</button></div>
    <p className="animation-hint">Runtime cells use whole-pixel placement and bottom-center pivot. Sheet dimensions are columns × rows × cell size. KangiFight geometry is locked by its game contract.</p>
    <div className="batch-controls"><label>Cell width<input className="text-input" type="number" disabled={project.preset === "kangi-fight"} value={cellWidth} onChange={e => { const width = Number(e.target.value); setCellWidth(width); if (workflow.anchorMode === "bottom-center") setPivotX(Math.floor(width / 2)); }} /></label><label>Cell height<input className="text-input" type="number" disabled={project.preset === "kangi-fight"} value={cellHeight} onChange={e => { const height = Number(e.target.value); setCellHeight(height); if (workflow.anchorMode === "bottom-center") setPivotY(height - 1); }} /></label><label>Pivot X<input className="text-input" type="number" disabled={project.preset === "kangi-fight" || workflow.anchorMode === "bottom-center"} value={pivotX} onChange={e => setPivotX(Number(e.target.value))} /></label><label>Pivot Y<input className="text-input" type="number" disabled={project.preset === "kangi-fight" || workflow.anchorMode === "bottom-center"} value={pivotY} onChange={e => setPivotY(Number(e.target.value))} /></label></div>
    {project.preset === "generic" && <div className="animation-actions"><button className="button secondary" disabled={busy || !runtimeValid} onClick={() => void updateRuntime(cellWidth, cellHeight, pivotX, pivotY)}><Check size={15} /> Save runtime geometry</button><small>Geometry locks after normalized artwork is applied.</small></div>}
  </details>;
}
